{
  'targets': [
    {
      'target_name': 'lazyload',
      # import all necessary source files
      'sources': [
        'llazyload.h', # this file was generated by go build
        'lazyload.cc'
      ],
      # libraries are relative to the 'build' directory
      'libraries': [ '../lazyload.a' ] # this file was also generated by go build
    }
  ]
}